name: Minify JSON

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20

      - name: Install tool
        run: npm i -g jsonzip

      - name: Minify and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git checkout minify
          git merge -X theirs main
          jsonzip
          git add .
          git commit -m "Minify JSON"
          git push origin minify